### ISSUE TITLE
ATOM autocomplete does not seem to work

### ISSUE THREAD

**Issue by Khachatour** [atom/autocomplete-atom-api#24]
I've had emmet installed, and some packages. Now I deleted them and disable some, but that does not seem to help autocomplete work properly, I do not have any completion yet, not in html nor css.  Any suggestions ? Thanks in advance.

**Comment by lee-dohm** [comment]
Emmet often interferes with Atom's autocompletion because of its overriding of the <kbd>Tab</kbd> key. Check out the [emmet README](https://atom.io/packages/emmet) for information on how it works. If you continue to have problems with autocomplete, see the links below.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
